// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMbDrJyj_2bLI-4GgCS0CYXG20WE5GvU',
    appId: '1:406908570322:web:381d6e321622db09f77b0b',
    messagingSenderId: '406908570322',
    projectId: 'impactforge-49',
    authDomain: 'impactforge-49.firebaseapp.com',
    storageBucket: 'impactforge-49.firebasestorage.app',
    measurementId: 'G-7ZJKCNVF9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH8adX8_57n02YVV1G3XxsfUGLRy1YafY',
    appId: '1:406908570322:android:281e495d746f8621f77b0b',
    messagingSenderId: '406908570322',
    projectId: 'impactforge-49',
    storageBucket: 'impactforge-49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRgBqxxrjzlNkgBVLO0e5djy3A344OqOU',
    appId: '1:406908570322:ios:75b14f8eb2bd5080f77b0b',
    messagingSenderId: '406908570322',
    projectId: 'impactforge-49',
    storageBucket: 'impactforge-49.firebasestorage.app',
    iosClientId: '406908570322-og6jace287ns1lgjn1pvc11lar1ouv22.apps.googleusercontent.com',
    iosBundleId: 'com.example.codenyx49',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRgBqxxrjzlNkgBVLO0e5djy3A344OqOU',
    appId: '1:406908570322:ios:75b14f8eb2bd5080f77b0b',
    messagingSenderId: '406908570322',
    projectId: 'impactforge-49',
    storageBucket: 'impactforge-49.firebasestorage.app',
    iosClientId: '406908570322-og6jace287ns1lgjn1pvc11lar1ouv22.apps.googleusercontent.com',
    iosBundleId: 'com.example.codenyx49',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMbDrJyj_2bLI-4GgCS0CYXG20WE5GvU',
    appId: '1:406908570322:web:9060a80c31f0dc07f77b0b',
    messagingSenderId: '406908570322',
    projectId: 'impactforge-49',
    authDomain: 'impactforge-49.firebaseapp.com',
    storageBucket: 'impactforge-49.firebasestorage.app',
    measurementId: 'G-3LDJK42DXN',
  );
}
